```{r}
#library(tidyverse)
library(reticulate)
options(
  reticulate.conda_binary = "C:/Users/ZE18RP/AppData/Local/anaconda3/Scripts/conda.exe"
)
use_condaenv("base", required = TRUE) # C:\Users\ZE18RP\AppData\Local\anaconda3\python.exe
reticulate::py_config()
#reticulate::repl_python()
```

```{r}
#reticulate::use_python("/usr/local/bin/python")
# If you haven't installed Python, the line below will prompt you!
#reticulate::py_install("pillow")
```

```{python}
# Note that while in Positron, we want to start the same _instance_ of python env.
# Therefore, we run the python code using reticulate using the function: py_run_string()

py_run_string("
import numpy as np
from PIL import Image
")
```

```{python}
# Note that while in Positron, we want to start the same _instance_ of python env.
# Therefore, we run the python code using reticulate using the function: py_run_string()

py_run_string("
im = Image.open(
    'C:/Users/ZE18RP/OneDrive - Aalborg Universitet/Skrivebord/courses/medicinsk-statistik/images/gorilla-waving-cartoon-black-white-outline-clipart-914.jpg'
)  # download at https://classroomclipart.com/clipart-view/Clipart/Black_and_White_Clipart/Animals/gorilla-waving-cartoon-black-white-outline-clipart-914_jpg.htm
pixels = np.asarray(im)

# Set threshold level
threshold_level = 50

# Find coordinates of all pixels below threshold
coords = np.column_stack(np.where(pixels < threshold_level))
")
```

```{r}
set.seed(28 - 4 + 2026)

coords <-
  as.data.frame(py$coords) |>
  dplyr::sample_n(1768) |>
  dplyr::mutate(
    age = (V2 / max(V2) * 60) + 30, # 98 - V2 * 200 / max(V2), #V2 * 17 + 15,
    maxHR = 200 - V1 * 200 / max(V1)
  ) |>
  dplyr::mutate(
    randvar = rnorm(dplyr::n(), mean = 0, sd = 10),
    randi = maxHR * (1 + randvar),
    ExAng = dplyr::case_when(randi < median(maxHR) ~ "no", TRUE ~ "Yes")
  )
```

```{r}
#| eval: false
coords |>
  dplyr::count(ExAng)
```

```{r}
#| eval: false
coords |>
  ggplot2::ggplot(ggplot2::aes(x = age, y = maxHR)) +
  ggplot2::geom_point() +
  ggplot2::theme_void() +
  ggplot2::xlim(0, 200)
```

```{r}
#| eval: false
coords |>
  ggplot2::ggplot(ggplot2::aes(x = age, y = maxHR, color = ExAng)) +
  ggplot2::geom_point() +
  #ggplot2::theme_void() +
  ggplot2::xlim(0, 100)
```
